name: build and deploy

on:
  push:
    branches:
      - develop

jobs:
  maven-build-and-deploy:
    uses: dmytro-kilchytskyi/workflows/maven-build-and-deploy.yml@main
    with:
      container-name: 'monobank-integration'
    secrets: inherit