name: build and deploy

on:
  push:
    branches:
      - test

jobs:
  maven-build-and-deploy:
    uses: dmytro-kilchytskyi/workflows/.github/workflows/maven-build-and-deploy.yml@feat/extract-docker
    with:
      container-name: 'monobank-integration'
    secrets: inherit